### ISSUE TITLE
Example: Dynamic Reload of Shaders

### ISSUE THREAD

**Issue by dskinner** [azul3d/oldissues#19]
Can be accomplished with fsnotify. Different editors save files in different ways which can complicate the implementation.

I'll put together a short sample of how I accomplished this later tonight. The example would perhaps be a simplified version of the following that I do:

* Keep shaders in a data/ directory
* Names by convention, so there would be a `triangle-vert.glsl` and `triangle-frag.glsl`
* When creating a new shader on an object, call `obj.Shader = gfx.NewShader("triangle")`
* During object rendering, first check if a shader has been compiled. If not, load the shader data.
* If fsnotify over shaders is enabled then:
    * When a file is changed, lookup objects using shader based on name, for example `triangle`
    * Mark each object shader as dirty
    * During object rendering, if shader is marked as dirty, reload the data

The example could provide some values in the shaders that encourage the user to change while the program is running.

See https://github.com/azul3d/gfx-gl2/issues/1

**Comment by slimsag** [comment]
This issue was moved to azul3d/engine#27
