### ISSUE TITLE
Tracking all issues

### ISSUE THREAD

**Issue by slimsag** [azul3d/oldissues#28]
@azul3d

Since we have so many separate repositories it's a bit hard for people to track all of the issues across them. I've had more than one person mention this to me. A few people have `watch`ed each repository, but I imagine it's a bit tedious to do so.

Does anyone have suggestions?

**Comment by slimsag** [comment]
@shurcooL In retrospect, something that does bother me about golang/go is that I get so many notification emails from it about things I'm not particularly interested in.

As far as I know there isn't a way for me to filter which issues in a repository I am notified of when I "watch" a repository, is there?

**Comment by shurcooL** [comment]
Personally, I use GitHub notifications and not their email notifications, and I find they're much easier to "wade through". Can mark many as read at a time if needed. See [here](https://cloud.githubusercontent.com/assets/1924134/5675160/9d2af274-976c-11e4-804c-f9a84eb54b33.png) for example.

> As far as I know there isn't a way for me to filter which issues in a repository I am notified of when I "watch" a repository, is there?

You can either watch or unwatch the entire repo, and you can subscribe or unsubscribe to individual issues.

![image](https://cloud.githubusercontent.com/assets/1924134/5675166/b56a50f0-976c-11e4-8557-9fa3e9b96441.png)

I don't think there's a more fine grained control. So yes, switching to all issues in one repo, people would lose the ability to watch some repos but not others.

**Comment by slimsag** [comment]
This issue was moved to azul3d/engine#39
