### ISSUE TITLE
Text package

### ISSUE THREAD

**Issue by 1l0** [azul3d/oldissues#31]
A noob question.
To show just a rune by keyboard typing, this works fine,
[gist/rune.go](https://gist.github.com/1l0/a8af4a624c725d7fca55)
but when I attempt to show runes as text within an object dynamically, this fails, 
[gist/dtext.go](https://gist.github.com/1l0/4516d262275627c69cc0)
this doesn't show appropriate texture for each rune.
Perhaps I should prepare specific shader for the mesh and texture array?

**Comment by slimsag** [comment]
This issue was moved to azul3d/engine#43
